import torch
from torch import Tensor
import torchmetrics
import typing
from typing import Union
import transformers
import os
import torch.nn.functional as F
from tqdm import tqdm
import math
import numpy as np 
from collections import Counter

LOG2 = torch.log(torch.tensor(2.0))

class NLL(torchmetrics.aggregation.MeanMetric):
  pass

class BPD(NLL):
  def compute(self) -> Tensor:
    """Computes the bits per dimension.

    Returns:
      bpd
    """
    return self.mean_value / self.weight / LOG2

class Perplexity(NLL):
  def compute(self) -> Tensor:
    """Computes the Perplexity.

    Returns:
      Perplexity
    """
    return torch.exp(self.mean_value / self.weight)

class NFEs(torchmetrics.aggregation.MeanMetric):
  pass

class Metrics:
  def __init__(self, config=None) -> None:
    self.config=config
    metrics = torchmetrics.MetricCollection({
        'nll': NLL(), 'bpd': BPD(), 'ppl': Perplexity()})
    if hasattr(config, 'block_size'):
      self.block_size = config.block_size
    else:
      self.block_size = config.model.length
      
    self.nfes = NFEs()
    self.train_nlls = metrics.clone(prefix='train/')
    self.valid_nlls = metrics.clone(prefix='val/')
    self.gen_ppl = Perplexity()
    self.gen_entropy = NLL()
    self.gen_ppls, self.gen_nfes, self.gen_entropies, self.gen_lengths \
      = [], [], [], []

    self.sampling_eps = config.training.sampling_eps
    if getattr(config.algo, 'clip_search_delta', None):
      self.clip_search_delta = config.algo.clip_search_delta
    self.valid_vars = {self.sampling_eps: []}
    if getattr(config.algo, 'var_min', None):
      self.valid_vars = self.init_valid_vars()
    self.eval_ppl_batch_size = \
     self.config.eval.perplexity_batch_size
    self.gen_ppl_eval_model_name_or_path = \
      config.eval.gen_ppl_eval_model_name_or_path
    self.tokenizer = transformers.AutoTokenizer.\
      from_pretrained(self.gen_ppl_eval_model_name_or_path)
    if self.tokenizer.pad_token is None:
      self.tokenizer.pad_token = self.tokenizer.eos_token
      self.tokenizer.pad_token_id = self.tokenizer.eos_token_id

  def init_valid_vars(self):
    eps = self.sampling_eps
    if self.block_size > 1:
      eps = self.sampling_eps
      self.valid_vars = {(eps, 1): []}
      for width in self.config.algo.clip_search_widths:
        for i in torch.arange(0, 1 - width + self.clip_search_delta, self.clip_search_delta):
          min = torch.clamp(i, min=self.sampling_eps).item()
          max = torch.clamp(i + width, min=self.sampling_eps).item()
          self.valid_vars[(min, max)] = []
    else:
      eps = self.sampling_eps
      self.valid_vars = {
        (eps, 1): [],
        (1, 1): []}


  def to(self, *args, **kwargs):
    self.train_nlls = self.train_nlls.to(*args, **kwargs)
    self.valid_nlls = self.valid_nlls.to(*args, **kwargs)
    self.gen_ppl = self.gen_ppl.to(*args, **kwargs)
    self.nfes = self.nfes.to(*args, **kwargs)
    self.gen_entropy = self.gen_entropy.to(*args, **kwargs)

  def reset(self):
    self.gen_ppls, self.gen_nfes, self.gen_entropies, self.gen_lengths \
      = [], [], [], []
    self.train_nlls.reset()
    self.valid_nlls.reset()
    self.gen_ppl.reset()
    self.gen_entropy.reset()
    self.nfes.reset()
    if getattr(self.config.algo, 'var_min', None):
      self.init_valid_vars()

  @torch.no_grad()
  def _eval_retokenize(self, text_samples, max_length,
                       device):
    """Retokenizes samples for the eval model.
    
    Args:
        text_samples: List of sentences generated by the model.
    Returns:
        samples: Samples re-tokenized for the eval model
        attn_mask: Attention mask for the eval model
        eval_context_size: Size of the context for the eval model
    """
    if 'llama2' in self.gen_ppl_eval_model_name_or_path:
      tokenizer_kwargs = {
        'text_samples': text_samples,
        'return_tensors': 'pt',
        'return_token_type_ids': False,
        'return_attention_mask': True,
        'truncation': True,
        'padding': True,
        'max_length': max_length,
      }
      eval_context_size = 4096
    else:
      tokenizer_kwargs = {
        'return_tensors': 'pt',
        'return_token_type_ids': False,
        'return_attention_mask': True,
        'truncation': True,
        'padding': True,
        'max_length': max_length,
      }
      eval_context_size = 1024
    samples = self.tokenizer(text_samples,
                             **tokenizer_kwargs)
    attn_mask = samples['attention_mask']
    samples = samples['input_ids']
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      attn_mask = attn_mask.to(device)
      samples = samples.to(device)      
    return samples, attn_mask, eval_context_size

  @torch.no_grad()
  def record_generative_perplexity(
    self,
    text_samples: typing.List[str],
    max_length: int,
    batch_size: Union[int, None] = None,
    retokenize: bool = True,
    stride=512,
    device='cuda') -> None:
    os.environ['TOKENIZERS_PARALLELISM'] = 'false'
    eval_model = transformers.AutoModelForCausalLM.from_pretrained(
      self.gen_ppl_eval_model_name_or_path).eval()
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      eval_model = eval_model.to(device)
    # Re-tokenize using eval model's tokenizer
    if retokenize:
      (samples, attn_mask,
       eval_context_size) = self._eval_retokenize(
         text_samples, max_length=max_length, device=device)
    else:
      samples = text_samples
      attn_mask = torch.ones(samples.shape).to(device)
      eval_context_size = samples.shape[-1]
    if batch_size is None:
      batch_size = min(self.eval_ppl_batch_size,
                      samples.shape[0])

    num_batches = samples.shape[0] // batch_size
    for i in range(num_batches):
      samples_batch = samples[i * batch_size: (i + 1) * batch_size]
      attn_mask_batch = attn_mask[i * batch_size: (i + 1) * batch_size]

      nlls_accum = torch.zeros_like(samples_batch, dtype=torch.float32)
      valid_tokens_accum = torch.zeros_like(samples_batch, dtype=torch.float32)

      num_strides = math.ceil((samples_batch.shape[-1] - eval_context_size + stride) / stride)
      num_strides = max(num_strides, 1)

      # Computes Gen. PPL in a sliding window for sequences longer than eval_context_size
      for i in tqdm(range(num_strides), desc='Sliding Window Gen PPL'):
        if i == 0:
          # for the first stride, use the entire eval_context_size
          start = 0
          end = min(eval_context_size, samples_batch.shape[-1])
        else:
          # then, move the window by stride
          start = i * stride
          end = min(start + eval_context_size, samples_batch.shape[-1])
        sample_chunk = samples_batch[..., start:end]
        attn_mask_chunk = attn_mask_batch[..., start:end]

        logits = eval_model(sample_chunk, attention_mask=attn_mask_chunk)[0]
        logits = logits.transpose(-1, -2)
        
        nlls = F.cross_entropy(logits[..., :-1], sample_chunk[..., 1:], reduction='none')
        valid_tokens = (sample_chunk[..., 1:] != self.tokenizer.eos_token_id).to(torch.float)
        
        if i == 0:
          # for the first stride, update the nlls of the entire eval_context_size
          nlls_accum[..., start + 1:end] += nlls
          valid_tokens_accum[..., start + 1:end] += valid_tokens
        else:
          # only update the nlls of the last stride
          update_start = (start+eval_context_size-stride)
          update_window = end - update_start
          nlls_accum[...,update_start:end] += nlls[..., -update_window:]
          valid_tokens_accum[..., update_start:end] += valid_tokens[..., -update_window:]
          
      # gen ppl
      avg_nll = (nlls_accum * valid_tokens_accum).sum() / valid_tokens_accum.sum()
      self.gen_ppls.append(avg_nll.exp().detach().cpu().item())
      self.gen_ppl.update(nlls_accum, valid_tokens_accum)

      # entropy
      entropy_full = 0
      for i in range(samples_batch.shape[0]):
        _, counts = torch.unique(samples_batch[i], return_counts=True, sorted=False)
        entropy = torch.special.entr(counts.float() / counts.sum()).sum()
        entropy_full += entropy
      self.gen_entropies.append(entropy_full.detach().cpu().item())
      self.gen_entropy.update(entropy_full, samples_batch.shape[0])

      # record sample length
      self.gen_lengths.append(valid_tokens_accum.sum().detach().cpu().item())

  @torch.no_grad()
  def record_block_efficiency_ratio(
      self,
      text_samples: typing.List[str],
      nfes_per_block: int,
      num_blocks: int,
      max_length: int = 1024,
      device: str = 'cuda'
  ) -> dict:
    """
    Computes Block Efficiency Ratio (BER) = Quality / Computational Cost
    """
    # Compute quality using existing gen_ppl infrastructure
    self.record_generative_perplexity(
        text_samples=text_samples,
        max_length=max_length,
        device=device
    )
    
    # Get the perplexity
    gen_ppl = self.gen_ppl.compute().item()
    quality_score = 1.0 / gen_ppl
    
    # Compute computational cost
    total_nfes = nfes_per_block * num_blocks
    
    # BER: quality per unit computation
    ber = quality_score / total_nfes
    
    result = {
        'block_efficiency_ratio': ber,
        'quality_score': quality_score,
        'generative_perplexity': gen_ppl,
        'total_nfes': total_nfes,
        'nfes_per_block': nfes_per_block,
        'num_blocks': num_blocks
    }
    
    return result

  @torch.no_grad()
  def record_time_to_first_block(
      self,
      generation_times: typing.List[float],
      block_size: int,
      model_length: int
  ) -> dict:
    """
    Computes Time-to-First-Block metrics from generation timings
    """
    
    avg_gen_time = np.mean(generation_times)
    num_blocks = model_length // block_size
    
    # Approximate time to first block
    time_per_block = avg_gen_time / num_blocks
    time_to_first_block_ms = time_per_block * 1000
    
    # Throughput
    throughput = model_length / avg_gen_time
    
    result = {
        'time_to_first_block_ms': float(time_to_first_block_ms),
        'time_per_block_ms': float(time_per_block * 1000),
        'avg_generation_time_s': float(avg_gen_time),
        'throughput_tokens_per_sec': float(throughput),
        'block_size': int(block_size)
    }
    
    return result

  @torch.no_grad()
  def record_block_variance_analysis(
      self,
      text_samples: typing.List[str],
      block_size: int,
      model_length: int,
      device: str = 'cuda'
  ) -> dict:
    """
    Analyzes variance in quality across different blocks within sequences.
    High variance suggests inconsistent generation quality.
    """
    os.environ['TOKENIZERS_PARALLELISM'] = 'false'
    eval_model = transformers.AutoModelForCausalLM.from_pretrained(
        self.gen_ppl_eval_model_name_or_path).eval()
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      eval_model = eval_model.to(device)
    
    samples, attn_mask, _ = self._eval_retokenize(
        text_samples, max_length=model_length, device=device)
    
    num_blocks = model_length // block_size
    block_ppls = []
    
    # Compute perplexity for each block position
    for block_idx in range(num_blocks):
      start = block_idx * block_size
      end = (block_idx + 1) * block_size
      
      block_samples = samples[:, start:end]
      block_attn = attn_mask[:, start:end]
      
      with torch.no_grad():
        logits = eval_model(block_samples, attention_mask=block_attn)[0]
        logits = logits.transpose(-1, -2)
        
        nlls = F.cross_entropy(logits[..., :-1], block_samples[..., 1:], reduction='none')
        valid_tokens = (block_samples[..., 1:] != self.tokenizer.eos_token_id).to(torch.float)
        
        avg_nll = (nlls * valid_tokens).sum() / valid_tokens.sum()
        block_ppl = torch.exp(avg_nll).item()
        block_ppls.append(block_ppl)
    
    result = {
        'block_ppl_mean': float(np.mean(block_ppls)),
        'block_ppl_std': float(np.std(block_ppls)),
        'block_ppl_min': float(np.min(block_ppls)),
        'block_ppl_max': float(np.max(block_ppls)),
        'block_ppl_range': float(np.max(block_ppls) - np.min(block_ppls)),
        'block_ppl_cv': float(np.std(block_ppls) / (np.mean(block_ppls) + 1e-10)),
        'per_block_ppls': [float(p) for p in block_ppls],
        'degradation_trend': float(np.corrcoef(range(len(block_ppls)), block_ppls)[0, 1])
    }
    
    return result

  @torch.no_grad()
  def record_sampling_efficiency_curve(
      self,
      samples_by_steps: typing.Dict[int, typing.List[str]],
      steps_list: typing.List[int],
      model_length: int,
      device: str = 'cuda'
  ) -> dict:
    """
    Analyzes quality vs sampling steps to find optimal T.
    Identifies diminishing returns and optimal operating points.
    """
    results = []
    
    for T in steps_list:
      samples = samples_by_steps[T]
      
      # Reset and compute PPL
      self.gen_ppl.reset()
      self.record_generative_perplexity(
          text_samples=samples,
          max_length=model_length,
          device=device
      )
      
      ppl = self.gen_ppl.compute().item()
      
      results.append({
          'diffusion_steps': int(T),
          'perplexity': float(ppl),
          'quality_improvement_per_step': 0.0  # Will compute after
      })
    
    # Compute marginal improvements
    for i in range(1, len(results)):
      ppl_improvement = results[i-1]['perplexity'] - results[i]['perplexity']
      step_difference = results[i]['diffusion_steps'] - results[i-1]['diffusion_steps']
      results[i]['quality_improvement_per_step'] = float(ppl_improvement / step_difference)
    
    # Find knee point (max marginal improvement)
    improvements = [r['quality_improvement_per_step'] for r in results[1:]]
    if improvements:
      knee_idx = np.argmax(improvements) + 1
      optimal_T = results[knee_idx]['diffusion_steps']
    else:
      optimal_T = steps_list[-1]
    
    return {
        'efficiency_curve': results,
        'optimal_T': int(optimal_T),
        'min_ppl_T': int(min(results, key=lambda x: x['perplexity'])['diffusion_steps']),
        'diminishing_returns_threshold': float(np.mean(improvements) if improvements else 0.0)
    }

  @torch.no_grad()
  def record_length_robustness(
      self,
      samples_by_length: typing.Dict[int, typing.List[str]],
      lengths: typing.List[int],
      device: str = 'cuda'
  ) -> dict:
    """
    Tests model performance across different sequence lengths.
    Important for validating arbitrary-length generation.
    """
    results = []
    
    for length in lengths:
      samples = samples_by_length[length]
      
      self.gen_ppl.reset()
      self.record_generative_perplexity(
          text_samples=samples,
          max_length=length,
          device=device
      )
      
      ppl = self.gen_ppl.compute().item()
      
      results.append({
          'sequence_length': int(length),
          'perplexity': float(ppl),
          'ppl_normalized': float(ppl / (length / 1024))  # Normalize to 1024 tokens
      })
    
    ppls = [r['perplexity'] for r in results]
    lengths_arr = [r['sequence_length'] for r in results]
    
    # Check if quality degrades with length
    correlation = np.corrcoef(lengths_arr, ppls)[0, 1]
    
    return {
        'length_robustness_curve': results,
        'length_ppl_correlation': float(correlation),
        'ppl_std_across_lengths': float(np.std(ppls)),
        'maintains_quality': bool(correlation < 0.3)  # Low correlation = robust
    }

  @torch.no_grad()
  def record_token_level_confidence(
      self,
      text_samples: typing.List[str],
      model_length: int,
      block_size: int,
      device: str = 'cuda'
  ) -> dict:
    """
    Analyzes model confidence at token level across blocks.
    Lower entropy = higher confidence.
    """
    os.environ['TOKENIZERS_PARALLELISM'] = 'false'
    eval_model = transformers.AutoModelForCausalLM.from_pretrained(
        self.gen_ppl_eval_model_name_or_path).eval()
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      eval_model = eval_model.to(device)
    
    samples, attn_mask, _ = self._eval_retokenize(
        text_samples, max_length=model_length, device=device)
    
    num_blocks = model_length // block_size
    block_confidences = []
    
    for block_idx in range(num_blocks):
      start = block_idx * block_size
      end = (block_idx + 1) * block_size
      
      block_samples = samples[:, start:end]
      block_attn = attn_mask[:, start:end]
      
      with torch.no_grad():
        logits = eval_model(block_samples, attention_mask=block_attn)[0]
        probs = F.softmax(logits, dim=-1)
        
        # Compute entropy (uncertainty) for each position
        entropies = -(probs * torch.log(probs + 1e-10)).sum(dim=-1)
        avg_entropy = entropies.mean().item()
        
        # Top-1 probability (confidence)
        top1_probs = probs.max(dim=-1)[0]
        avg_confidence = top1_probs.mean().item()
        
        block_confidences.append({
            'block_idx': block_idx,
            'avg_entropy': float(avg_entropy),
            'avg_confidence': float(avg_confidence)
        })
    
    entropies = [b['avg_entropy'] for b in block_confidences]
    confidences = [b['avg_confidence'] for b in block_confidences]
    
    return {
        'per_block_confidence': block_confidences,
        'overall_avg_entropy': float(np.mean(entropies)),
        'overall_avg_confidence': float(np.mean(confidences)),
        'entropy_std': float(np.std(entropies)),
        'confidence_std': float(np.std(confidences)),
        'first_block_confidence': float(confidences[0]) if confidences else 0.0,
        'last_block_confidence': float(confidences[-1]) if confidences else 0.0
    }

  @torch.no_grad()
  def record_repetition_metrics(
      self,
      text_samples: typing.List[str],
      n_gram_sizes: typing.List[int] = [2, 3, 4]
  ) -> dict:
    """
    Measures repetition at different n-gram levels.
    High repetition indicates mode collapse or poor diversity.
    """
    def get_ngrams(tokens, n):
      return [tuple(tokens[i:i+n]) for i in range(len(tokens)-n+1)]
    
    results = {}
    
    for n in n_gram_sizes:
      all_ngrams = []
      unique_ratios = []
      max_repetitions = []
      
      for sample in text_samples:
        tokens = self.tokenizer.encode(sample, add_special_tokens=False)
        ngrams = get_ngrams(tokens, n)
        
        if not ngrams:
          continue
        
        all_ngrams.extend(ngrams)
        
        # Unique ratio for this sample
        unique_ratio = len(set(ngrams)) / len(ngrams)
        unique_ratios.append(unique_ratio)
        
        # Max repetition count
        ngram_counts = Counter(ngrams)
        max_rep = max(ngram_counts.values()) if ngram_counts else 1
        max_repetitions.append(max_rep)
      
      # Overall statistics
      overall_ngram_counts = Counter(all_ngrams)
      overall_unique_ratio = len(set(all_ngrams)) / len(all_ngrams) if all_ngrams else 0
      
      results[f'{n}gram'] = {
          'unique_ratio_mean': float(np.mean(unique_ratios)) if unique_ratios else 0.0,
          'unique_ratio_std': float(np.std(unique_ratios)) if unique_ratios else 0.0,
          'max_repetition_mean': float(np.mean(max_repetitions)) if max_repetitions else 0.0,
          'overall_unique_ratio': float(overall_unique_ratio),
          'total_ngrams': len(all_ngrams),
          'unique_ngrams': len(set(all_ngrams))
      }
    
    # Repetition score (lower is better)
    # Average across n-gram sizes
    avg_unique_ratio = np.mean([results[f'{n}gram']['unique_ratio_mean'] for n in n_gram_sizes])
    repetition_score = 1.0 - avg_unique_ratio
    
    results['summary'] = {
        'overall_repetition_score': float(repetition_score),
        'avg_unique_ratio': float(avg_unique_ratio),
        'has_excessive_repetition': bool(repetition_score > 0.3)
    }
    
    return results

  @torch.no_grad()
  def record_computational_breakdown(
      self,
      generation_times: typing.List[float],
      block_size: int,
      model_length: int,
      diffusion_steps: int
  ) -> dict:
    """
    Breaks down computational costs across different components.
    Helps identify bottlenecks.
    """
    num_blocks = model_length // block_size
    avg_time = np.mean(generation_times)
    
    # Theoretical breakdown
    time_per_block = avg_time / num_blocks
    time_per_diffusion_step = time_per_block / diffusion_steps
    
    # Compare with autoregressive baseline (sequential token generation)
    ar_time_per_token = time_per_block / block_size  # Approximate
    ar_total_time = ar_time_per_token * model_length
    
    # Speedup metrics
    theoretical_max_speedup = block_size
    actual_speedup = ar_total_time / avg_time if avg_time > 0 else 0
    efficiency = (actual_speedup / theoretical_max_speedup) * 100 if theoretical_max_speedup > 0 else 0
    
    result = {
        'total_generation_time_s': float(avg_time),
        'time_per_block_ms': float(time_per_block * 1000),
        'time_per_diffusion_step_ms': float(time_per_diffusion_step * 1000),
        'tokens_per_second': float(model_length / avg_time) if avg_time > 0 else 0,
        'blocks_per_second': float(num_blocks / avg_time) if avg_time > 0 else 0,
        'diffusion_steps_per_second': float((num_blocks * diffusion_steps) / avg_time) if avg_time > 0 else 0,
        'estimated_ar_time_s': float(ar_total_time),
        'speedup_vs_ar': float(actual_speedup),
        'theoretical_max_speedup': float(theoretical_max_speedup),
        'parallel_efficiency_pct': float(efficiency),
        'overhead_per_block_ms': float(max(0, time_per_block - (diffusion_steps * time_per_diffusion_step)) * 1000)
    }
    
    return result

  @torch.no_grad()
  def record_quality_consistency(
      self,
      text_samples: typing.List[str],
      model_length: int,
      device: str = 'cuda',
      num_runs: int = 3
  ) -> dict:
    """
    Measures consistency across multiple generation runs with same config.
    Low variance indicates stable generation.
    """
    run_ppls = []
    
    for run_idx in range(min(num_runs, len(text_samples) // 5)):
      # Take subset for each run
      start_idx = run_idx * (len(text_samples) // num_runs)
      end_idx = start_idx + (len(text_samples) // num_runs)
      run_samples = text_samples[start_idx:end_idx]
      
      if not run_samples:
        continue
      
      self.gen_ppl.reset()
      self.record_generative_perplexity(
          text_samples=run_samples,
          max_length=model_length,
          device=device
      )
      
      ppl = self.gen_ppl.compute().item()
      run_ppls.append(ppl)
    
    return {
        'ppl_mean': float(np.mean(run_ppls)) if run_ppls else 0.0,
        'ppl_std': float(np.std(run_ppls)) if run_ppls else 0.0,
        'ppl_min': float(np.min(run_ppls)) if run_ppls else 0.0,
        'ppl_max': float(np.max(run_ppls)) if run_ppls else 0.0,
        'coefficient_of_variation': float(np.std(run_ppls) / (np.mean(run_ppls) + 1e-10)) if run_ppls else 0.0,
        'is_consistent': bool(np.std(run_ppls) < 5.0) if run_ppls else False,
        'num_runs': len(run_ppls)
    }
